-- MySQL Script generated by MySQL Workbench
-- Срд 13 лют 2019 10:57:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8;
USE mydb ;

-- -----------------------------------------------------
-- Table mydb.teacher
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.teacher (
  login_teach VARCHAR(45) NOT NULL,
  teacher_first_name VARCHAR(45) NOT NULL,
  teacher_last_name VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  UNIQUE INDEX login_teach_UNIQUE (login_teach ASC),
  PRIMARY KEY (login_teach))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.subject
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.subject (
  id_subject INT NOT NULL,
  subject VARCHAR(60) NULL,
  PRIMARY KEY (id_subject))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.student
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.student (
  id_student INT UNSIGNED NOT NULL,
  student_first_name VARCHAR(45) NOT NULL,
  student_last_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_student))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.tests
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.tests (
  id_tests INT NOT NULL,
  test_name VARCHAR(45) NULL,
  teacher_login_teach VARCHAR(45) NOT NULL,
  subject_id_subject INT NOT NULL,
  student_id_student INT UNSIGNED NOT NULL,
  PRIMARY KEY (id_tests, teacher_login_teach, subject_id_subject),
  INDEX fk_tests_teacher1_idx (teacher_login_teach ASC),
  INDEX fk_tests_subject1_idx (subject_id_subject ASC),
  INDEX fk_tests_student1_idx (student_id_student ASC),
  CONSTRAINT fk_tests_teacher1
    FOREIGN KEY (teacher_login_teach)
    REFERENCES mydb.teacher (login_teach)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_tests_subject1
    FOREIGN KEY (subject_id_subject)
    REFERENCES mydb.subject (id_subject)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_tests_student1
    FOREIGN KEY (student_id_student)
    REFERENCES mydb.student (id_student)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.questions
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.questions (
  id_test_question INT NOT NULL,
  test_question VARCHAR(200) NOT NULL,
  subject_id_subject INT NOT NULL,
  PRIMARY KEY (id_test_question, subject_id_subject),
  INDEX fk_questions_subject1_idx (subject_id_subject ASC),
  CONSTRAINT fk_questions_subject1
    FOREIGN KEY (subject_id_subject)
    REFERENCES mydb.subject (id_subject)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.question_items
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.question_items (
  id_question_item INT NOT NULL,
  question_item VARCHAR(200) NOT NULL,
  PRIMARY KEY (id_question_item))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.questions_has_question_items
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.questions_has_question_items (
  questions_id_test_question INT NOT NULL,
  questions_subject_id_subject INT NOT NULL,
  question_items_id_question_item INT NOT NULL,
  answer TINYINT(1) NOT NULL,
  PRIMARY KEY (questions_id_test_question, questions_subject_id_subject, question_items_id_question_item),
  INDEX fk_questions_has_question_items_question_items1_idx (question_items_id_question_item ASC),
  INDEX fk_questions_has_question_items_questions1_idx (questions_id_test_question ASC, questions_subject_id_subject ASC),
  CONSTRAINT fk_questions_has_question_items_questions1
    FOREIGN KEY (questions_id_test_question , questions_subject_id_subject)
    REFERENCES mydb.questions (id_test_question , subject_id_subject)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_questions_has_question_items_question_items1
    FOREIGN KEY (question_items_id_question_item)
    REFERENCES mydb.question_items (id_question_item)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.student_answer
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.student_answer (
  questions_has_question_items_questions_id_test_question INT NOT NULL,
  questions_has_question_items_questions_subject_id_subject INT NOT NULL,
  questions_has_question_items_question_items_id_question_item INT NOT NULL,
  student_id_student INT UNSIGNED NOT NULL,
  PRIMARY KEY (questions_has_question_items_questions_id_test_question, questions_has_question_items_questions_subject_id_subject, questions_has_question_items_question_items_id_question_item, student_id_student),
  INDEX fk_student_answer_student1_idx (student_id_student ASC),
  CONSTRAINT fk_student_answer_questions_has_question_items1
    FOREIGN KEY (questions_has_question_items_questions_id_test_question , questions_has_question_items_questions_subject_id_subject , questions_has_question_items_question_items_id_question_item)
    REFERENCES mydb.questions_has_question_items (questions_id_test_question , questions_subject_id_subject , question_items_id_question_item)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_student_answer_student1
    FOREIGN KEY (student_id_student)
    REFERENCES mydb.student (id_student)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
